import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { ConfigProvider } from "antd";
import GlobalStyleProvider from "@/components/GlobalStyleProvider";
import AntdRegistry from "@ant-design/nextjs-registry/lib/AntdRegistry";
import StyledComponentsRegistry from "@/components/styled-registry";
import NaverMapProvider from "@/components/NaverMapProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <GlobalStyleProvider />
      <html lang="ko">
        <head>
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body>
          <StyledComponentsRegistry>
            <AntdRegistry>
              <ConfigProvider
                theme={{
                  components: { Button: { borderRadius: 4, boxShadow: "none" } },
                }}
              >
                <Suspense>
                  <NaverMapProvider>
                    <ConfigProvider>{children}</ConfigProvider>
                  </NaverMapProvider>
                </Suspense>
              </ConfigProvider>
            </AntdRegistry>
          </StyledComponentsRegistry>
        </body>
      </html>
    </>
  );
}
